<?php
/** @var \Magento\Catalog\Block\Product\View $block */
?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Pmclain_OneClickCheckout/js/buy-now": {
                "isAvailableUrl": "<?php echo $block->getUrl('rest/V1/buttons/buynow/canshow/') ?>",
                "submitUrl": "<?php echo $block->getUrl('buynow/oneclick/placeorder') ?>"
            }
        }
    }
</script>

<script id="occ-template" type="text/x-occ-template">
    <button type="button" title="<?php echo __('One Click Checkout') ?>" class="action primary occ" id="product-oneclick-button">
        <span><?php echo __('One Click Checkout') ?></span>
    </button>
</script>

<script type="text/template" class="order-template">
    <div id="one-click-confirmation">
        <h3><?php echo __('Your order number is') ?> <a href="<%- order.url %>"><%- order.incrementId %></a></h3>
        <table>
            <tr>
                <td><strong><?php echo __('Subtotal') ?></strong></td>
                <td><%- order.totals.subtotal %></td>
            </tr>
            <% if (order.totals.discount.raw) { %>
                <tr>
                    <td><strong><?php echo __('Discount') ?></strong></td>
                    <td><%- order.totals.discount.formatted %></td>
                </tr>
            <% } %>
            <% if (order.totals.shipping.raw) { %>
                <tr>
                    <td><strong><?php echo __('Shipping') ?></strong></td>
                    <td><%- order.totals.shipping.formatted %></td>
                </tr>
            <% } %>
            <% if (order.totals.tax.raw) { %>
            <tr>
                <td><strong><?php echo __('Tax') ?></strong></td>
                <td><%- order.totals.tax.formatted %></td>
            </tr>
            <% } %>
            <tr>
                <td><strong><?php echo __('Grand Total') ?></strong></td>
                <td><%- order.totals.grandTotal %></td>
            </tr>
        </table>
    </div>
</script>
